"""intial commit table creation

Revision ID: c00f52d195fe
Revises: 
Create Date: 2026-02-05 22:15:14.668068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c00f52d195fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'reference_id', 'channel', name='uq_event_reference_channel')
    )
    op.create_index(op.f('ix_notification_requests_id'), 'notification_requests', ['id'], unique=False)
    op.create_index(op.f('ix_notification_requests_reference_id'), 'notification_requests', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notification_requests_user_id'), 'notification_requests', ['user_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code', 'channel', name='uq_template_code_channel')
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_table('notification_failures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_failures_id'), 'notification_failures', ['id'], unique=False)
    op.create_index(op.f('ix_notification_failures_notification_id'), 'notification_failures', ['notification_id'], unique=False)
    op.create_table('notification_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('recipient', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=150), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_messages_id'), 'notification_messages', ['id'], unique=False)
    op.create_index(op.f('ix_notification_messages_notification_id'), 'notification_messages', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_messages_notification_id'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_id'), table_name='notification_messages')
    op.drop_table('notification_messages')
    op.drop_index(op.f('ix_notification_failures_notification_id'), table_name='notification_failures')
    op.drop_index(op.f('ix_notification_failures_id'), table_name='notification_failures')
    op.drop_table('notification_failures')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_requests_user_id'), table_name='notification_requests')
    op.drop_index(op.f('ix_notification_requests_reference_id'), table_name='notification_requests')
    op.drop_index(op.f('ix_notification_requests_id'), table_name='notification_requests')
    op.drop_table('notification_requests')
    # ### end Alembic commands ###
